### ISSUE TITLE
Implement bubble sort in Java

### ISSUE THREAD

**Issue by shari09** [deutranium/Algorithms#144]
Implement bubble sort in Java

**Comment by MercerFrey** [comment]
may i take it :)

**Comment by shari09** [comment]
Do I just open an issue and make a PR myself. If so, I've already done that :)

**Comment by MercerFrey** [comment]
yeah, im newbie sorry about that

**Comment by deutranium** [comment]
@shari09 yupp, just ensure that no one else is working on it when you want to.
Saw you PR, I'll review it asap

**Comment by deutranium** [comment]
Closing this with #145
