### ISSUE TITLE
String Palindrome checker

### ISSUE THREAD

**Issue by AtigPurohit** [deutranium/Algorithms#161]
I can make a program to check whether a string is palindrome or not.

Languages:

- [ ] C++
- [ ] Java

**Comment by deutranium** [comment]
Hey @AtigPurohit 
Sure you can also look at the python implementation here for reference!

Happy coding!

**Comment by deutranium** [comment]
Closed with #162

**Comment by codelixir** [comment]
Hey, can I implement this in golang?

**Comment by inesane** [comment]
@codelixir Sure go ahead!

**Comment by codelixir** [comment]
Closed with #176

**Comment by codelixir** [comment]
@gabrielhs1357 assigned! Looks like you accidentally closed the PR by force-pushing. Please reopen it so that I can merge it.

**Comment by skywalker2207** [comment]
@codelixir can you assign this issue to me I will implement it in c#

**Comment by codelixir** [comment]
@skywalker2207 C# has already been implemented in #213. You can also do it in a language not listed above.
