### ISSUE TITLE
Implement the Perceptron Algorithm in Python Language.

### ISSUE THREAD

**Issue by Lashuk1729** [deutranium/Algorithms#178]

**Comment by Lashuk1729** [comment]
@deutranium I would like to work on this issue.

**Comment by codelixir** [comment]
I think she's busy so I'll reply on her behalf.
@Lashuk1729 you can work on it. Also, it would be great if you could provide a small description of the algorithm :)

**Comment by Lashuk1729** [comment]
@deutranium @codelixir Please do take a look and let me know if any changes are needed to be made.

**Comment by codelixir** [comment]
Closing with #180 
Thanks @Lashuk1729
