### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by shubham2704** [deutranium/Algorithms#36]
Quick sort algorithm is missing in sorting algorithms folder.

I would like to work on this.

**Comment by deutranium** [comment]
Sure!!
Do add it in readme.md and check up contributing guidelines before making a PR

**Comment by aedorado** [comment]
@shubham2704 What language are you adding?

**Comment by deutranium** [comment]
@aedorado he has added Python and JavaScript

**Comment by deutranium** [comment]
Closing this issue with #39 
I'll create a new one with the same format as others. Good job on the linked PR with creating and adding it to readme etc.

**Comment by shubham2704** [comment]
> Closing this issue with #39
> I'll create a new one with the same format as others. Good job on the linked PR with creating and adding it to readme etc.

Thank you for merging my pull request, i will try to solve other issues also.✌

**Comment by deutranium** [comment]
@shubham2704 sure :)
Thanks for contributing!!
