### ISSUE TITLE
Implement Kruskals algorithm 

### ISSUE THREAD

**Issue by arushimgupta** [deutranium/Algorithms#80]
Implemented the Kruskals algorithm to find Minimum Spanning Tree of a Graph

**Comment by adithyaakrishna** [comment]
@arushimgupta I Would really suggest you to add some description to the issue and Change the title to Implement Kruskals Algorithm
And it would be really good if Hacktoberfest is treated to be a oppurtunity to learn and code and hence contribute to Open Source. Please don't create issues or Spam the Hacktoberfest

Happy Hacking! 🚀

**Comment by deutranium** [comment]
@arushimgupta sure but it is always better to create the issue before you start working on the code. Please keep this in mind for your future contributions.

**Comment by deutranium** [comment]
Closing this with #82
